# Generated by Django 2.2.1 on 2019-07-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(blank=True, max_length=140, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('head_img', models.ImageField(blank=True, upload_to='head_img/%Y%m%d/')),
                ('follow_list', models.ManyToManyField(blank=True, related_name='my_followers', to='uiweb.UserProfile')),
                ('tags', models.ManyToManyField(to='uiweb.Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_type', models.IntegerField(choices=[(0, 'new'), (1, 'forward'), (2, 'collect')], default=0)),
                ('text', models.CharField(max_length=140)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='wb_pic/%Y%m%d')),
                ('pictures_link_id', models.CharField(blank=True, max_length=128, null=True)),
                ('video_link_id', models.CharField(blank=True, max_length=128, null=True)),
                ('perm', models.IntegerField(choices=[(0, 'public'), (1, 'private'), (2, 'friends')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('forward_or_collect_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_or_collects', to='uiweb.Weibo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiweb.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(choices=[(0, 'comment'), (1, 'thumb_up')], default=0)),
                ('comment', models.CharField(max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='uiweb.Comment')),
                ('to_weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiweb.Weibo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiweb.UserProfile')),
            ],
        ),
    ]
