# Generated by Django 2.2.1 on 2019-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='wb_pic/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, upload_to='head_img/%Y%m%d/'),
        ),
    ]
