# Generated by Django 2.2.1 on 2019-06-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiweb', '0002_auto_20190617_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='wb_pic/%Y%m%d'),
        ),
    ]
