# Generated by Django 2.2.1 on 2019-06-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiweb', '0003_auto_20190617_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='weibo_id',
            field=models.IntegerField(default=0),
        ),
    ]
