# Generated by Django 2.2.1 on 2019-06-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uiweb', '0005_auto_20190621_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='forward_or_collect_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_or_collects', to='uiweb.Weibo'),
        ),
    ]
