# Generated by Django 2.2.1 on 2019-06-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uiweb', '0006_weibo_forward_or_collect_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiweb.Weibo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiweb.UserProfile')),
            ],
        ),
    ]
