# Generated by Django 2.2.1 on 2019-06-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiweb', '0007_zan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zan',
            name='user',
        ),
        migrations.AddField(
            model_name='zan',
            name='user',
            field=models.ManyToManyField(to='uiweb.UserProfile'),
        ),
    ]
